module.exports = {
    approval:       ['\uE085',          '\uE085'        ],
    bomb:           ['\ud83d\udca3'                     ],
    burger:         ['\uE159',          '\uE159'        ],
    calendar:       ['\ud83d\udcc5',    '\ud83d\udcc5'  ],
    camera:         ['\ud83d\udcf7',    '\ud83d\udcf7'  ],
    chevronback:    ['\uE225',          '\uE079'        ],
    chevronforward: ['\uE224',          '\uE080'        ],
    circleinfo:     ['\uE196',          '\uE086'        ],
    circleminus:    ['\uE192'                           ],     
    circletick:     ['\uE194',          '\uE084'        ],
    clock:          ['\uE055',          '\uE023'        ],     
    clouddownload:  ['\uE364',          '\uE364'        ],
    cloudupload:    ['\uE365',          '\uE198'        ],
    cog:            ['\uE137',          '\uE019'        ],
    comment:        ['\uE246',          '\uE111'        ],
    conversation:   ['\uE245'                           ],     
    cross:          ['\uE208',          '\uE014'        ],
    cycle:          ['\uE082',          '\uE031'        ],
    decision:       ['\uE423'                           ],     
    edit:           ['\u270F',          '\u270F'        ],       
    ellipsis:       ['\uE188'                           ],     
    end:            ['\uE192'                           ],     
    envelope:       ['\u2709'                           ],     
    eye:            ['\uE052',          '\uE105'        ],
    fastForward:    ['\uE177',          '\uE075'        ],
    file:           ['\uE037',          '\uE022'        ],
    film:           ['\uE009'                           ],
    filter:         ['\uE321'                           ],     
    folder:         ['\uE441',          '\uE117'        ],
    fullscreen:     ['\uE216'                           ],     
    grid:           ['\uE157',          '\uE011'        ],
    group:          ['\uE044',                          ],     
    inbox:          ['\uE131',          '\uE028'        ],
    keyboard:       ['\uE270'                           ],     
    lightening:     ['\uE242',          '\uE162'        ],
    list:           ['\uE115',          '\uE012'        ],
    logout:         ['\uE388',          '\uE163'        ],
    megaphone:      ['\uE356',          '\uE122'        ],
    minus:          ['\u2212',          '\u2212'        ],
    muted:          ['\uE183',          '\uE036'        ],
    no:             ['\uE200',          '\uE090'        ],
    paperclip:      ['\ud83d\udcce',    '\ud83d\udcce'  ],
    pause:          ['\uE175'                           ],
    person:         ['\uE004',          '\uE008'        ],
    play:           ['\uE174',          '\uE174'        ],
    plus:           ['\u002B',          '\u002B'        ],
    print:          ['\uE016'                           ],
    qrcode:         ['\uE259',          '\uE039'        ],
    rabbit:         ['\ud83d\udc07'                     ],
    sampler:        ['\uE328'                           ],
    search:         ['\uE028',          '\uE003'        ],
    share:          ['\uE223',          '\uE095'        ],
    share_alt:      ['\uE309'                           ],
    sort:           ['\uE404'                           ],
    start:          ['\uE174'                           ],
    table:          ['\uE120'                           ],
    tag:            ['\uE067',          '\uE042'        ],
    task:           ['\uE359'                           ],     
    thumbsdown:     ['\uE345',          '\uE126'        ],
    tick:           ['\uE207',           '\uE013'        ],     
    trash:          ['\uE017',          '\uE020'        ],
    undo:           ['\uE222'                           ],     
    unfullscreen:   ['\uE215'                           ],     
    unmuted:        ['\uE185',          '\uE038'        ],
    weights:        ['\uE357'                           ],     
    warning:        ['\uE079'                           ],     
    world:          ['\uE371',          '\uE135'        ]
};